name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git remote URL
      run: git remote set-url origin https://github.com/GorkemErtas/SE3355_BuySellWebsite.git

    - name: Pull from remote to sync branches
      run: git pull origin main --rebase

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: my-buy-sell-web
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
